Update Nuget packages to latest
Need to update the Nuget packages to more recent versions in order to update the `PlatformTool` setting.

----

The GoogleTest 1.8.1.3 package does not support Visual Studio 2022's `PlatformToolset` of `v143`. It needs to be updated in order for automatic linking to work with newer `PlatformToolset` values.

Attempting to use the Nuget package for GoogleTest with version `1.8.1.3` with `PlatformToolset` of `v143` produces the following error:
>          LIBCMT.lib(exe_main.obj) : error LNK2001: unresolved external symbol main [D:\a\OP2Utility\OP2Utility\test\OP2UtilityTest.vcxproj]
>          D:\a\OP2Utility\OP2Utility\x64\Release\OP2UtilityTest.exe : fatal error LNK1120: 1 unresolved externals [D:\a\OP2Utility\OP2Utility\test\OP2UtilityTest.vcxproj]

The unit test project is setup to link `main` from the `gtest_main.lib` library file from the Nuget package for GoogleTest. Since automatic linking is disabled for the newer `PlatformToolset` value, the link step fails.

----

Details:
Nuget package page:
https://www.nuget.org/packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-static/1.8.1.3

Package explorer:
https://nuget.info/packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-static/1.8.1.3

Details of how the build system uses this package are found in:
`build/native/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-static.targets`

There is a `Condition` check that depends on `PlatformToolset`, and if it's not one of `v142`, `v141`, or `v140`, then by default it sets a disable flag that prevents automatic linking with the packaged library files. In particular `v143` and newer are not supported for automatic linking. This prevents linking against `gtest.lib` and `gtest_main.lib`. The `gtest_main.lib` file is where the `main` method is linked from, hence the error message about the "unresolved external symbol main".