Remove Slice from SeekableStreamReader
 - Remove unique_ptr from return of Slice function from FileSreamReader and FileSliceReader
 - Make one version of Slice function as const

Causes the following compile time error on MSVC:

Error C2280 'FileSliceReader::FileSliceReader(const FileSliceReader &)': attempting to reference a deleted function
OP2Utility c:\ . . . \op2utility\streams\filestreamreader.cpp 45

Likely caused because there FileSliceReader does not have a copy constructor defined due to the contained underlying std::ifstream.